- hosts: all
  become: true

  tasks:

    - name: ensure docker and dependencies are installed
      apt: name=docker.io update_cache=yes

    - name: 'add user to docker group'
      user:
        name: 'ubuntu'
        groups: 'docker'
        append: 'yes'

    - service: name=docker state=restarted
